# Generated by Django 2.1 on 2018-11-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoardStudent', '0002_remove_userlogin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='isProvost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='isStudent',
            field=models.BooleanField(default=False),
        ),
    ]
