# Generated by Django 2.1 on 2018-11-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoardStudent', '0003_auto_20181108_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='username',
            field=models.CharField(default='username', max_length=120),
        ),
    ]
