# Generated by Django 2.1 on 2018-11-12 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=120)),
                ('lname', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='roomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eNo', models.CharField(max_length=6)),
                ('Name', models.CharField(max_length=120)),
                ('FacNo', models.CharField(max_length=10)),
                ('current_standing', models.IntegerField(default=0)),
                ('room', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashBoardProvost.roomModel')),
            ],
        ),
    ]
