# Generated by Django 2.1 on 2018-11-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoardProvost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='room_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roommodel',
            name='seat_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
