# Generated by Django 2.1 on 2018-11-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoardProvost', '0002_auto_20181112_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='room',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='room',
            field=models.ManyToManyField(to='dashBoardProvost.roomModel'),
        ),
    ]
