# Generated by Django 2.1 on 2018-11-12 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoardProvost', '0003_auto_20181112_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='room',
        ),
        migrations.AddField(
            model_name='roommodel',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashBoardProvost.studentModel'),
        ),
    ]
